### ISSUE TITLE
이름을 가질 수 있다가 멤버 변수으로 name을 의미하는 것이 맞나요?

### ISSUE THREAD

**Issue by swsz2** [hyehwanchoi/effective-java-third#1]
저는 **메소드 명으로 어떠한 객체에 대한 설명을 할 수 있다**로 이해를 했었는데요.
저와 이해한 내용이 다른 거 같아서요...
제가 엉뚱한 방향으로 이해했을 수도 있으니 한번 확인해주세요

https://github.com/hyehwanchoi/effective-java-third/blob/master/src/main/java/item1/Code1.java

**Comment by hyehwanchoi** [comment]
앗 제가 헷갈리게 코드를 작성한 것 같네요.
'이름을 명시적으로 묘사' 에 집중하여 getName, getCode 를 작성하여 나타냈어요

**Comment by choi-muhayu** [comment]
getName getCode에서 각각 name과 code를 넘겨서 객체를 받도록 되어 있는데요, 
아래와 같이 좀 더 함수명을 구채적으로 주는 것이 더 좋을 것 같습니다.

Code1.newInstance(String name) 
Code1.newInstanceWithName(String name) 

Code1.newInstance(int code) 
Code1.newInstanceWithName(int code) 



static으로 구현하였다고 하더라도 getName 같은 경우 getter의 매소드명과 동일해서 가독성에 영향이 있을 것 같아요.

물론 builder 패턴을 사용할 수도 있겠습니다.

**Comment by chh-muhayu** [comment]
그러네요.. 참고해서 수정할게요 !
